# Generated by Django 5.2.3 on 2025-06-28 09:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("customer_service", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="faq",
            name="category",
            field=models.CharField(default="常见问题", max_length=50),
        ),
        migrations.AddField(
            model_name="faq",
            name="is_main",
            field=models.BooleanField(default=False),
        ),
    ]
