# Generated by Django 5.2.3 on 2025-06-30 01:00

import customer_service.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer_service', '0003_profile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='avatar',
            field=models.ImageField(blank=True, null=True, upload_to=customer_service.models.avatar_upload_path, verbose_name='头像'),
        ),
    ]
